# Generated by Django 3.0.8 on 2020-07-28 13:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_auto_20200728_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservations',
            name='checkin_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservations',
            name='num_of_days',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservations',
            name='num_of_guests',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
