# Generated by Django 3.0.8 on 2020-07-28 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_auto_20200728_1631'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservations',
            name='token',
        ),
    ]
