# Generated by Django 3.0.8 on 2020-07-29 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0006_auto_20200729_0302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservations',
            name='status',
            field=models.CharField(choices=[('RESERVED', 'RESERVED'), ('CANCELED', 'CANCELED'), ('CHECKED_IN', 'CHECKED_IN'), ('CHECKED_OUT', 'CHECKED_OUT')], default='RESERVED', max_length=32),
        ),
    ]
