# Generated by Django 3.0.8 on 2020-07-29 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0007_auto_20200729_0531'),
        ('reservations', '0007_auto_20200729_1359'),
    ]

    operations = [
    ]
