# Generated by Django 3.0.8 on 2020-07-29 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0007_auto_20200729_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservations',
            name='person_group_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
