# Generated by Django 3.0.8 on 2020-07-29 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0008_reservations_person_group_id'),
        ('reservations', '0008_merge_20200729_0901'),
    ]

    operations = [
    ]
