# Generated by Django 3.0.8 on 2020-07-28 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0001_initial'),
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('passport', models.CharField(blank=True, max_length=64, null=True)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='uploads/')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guests_rooms', to='reservations.Reservations')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guests_reservations', to='rooms.Rooms')),
            ],
        ),
    ]
