# Generated by Django 3.0.8 on 2020-07-28 10:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0002_remove_guests_room'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guests',
            old_name='image',
            new_name='image_sample_1',
        ),
        migrations.AddField(
            model_name='guests',
            name='image_sample_2',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='uploads/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guests',
            name='image_sample_3',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='uploads/'),
            preserve_default=False,
        ),
    ]
