# Generated by Django 3.0.8 on 2020-07-28 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0003_auto_20200728_1308'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guests',
            options={'verbose_name': 'Guest', 'verbose_name_plural': 'Guests'},
        ),
    ]
