# Generated by Django 3.0.8 on 2020-07-28 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0004_auto_20200728_1450'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('file', models.ImageField(null=True, upload_to='uploads/')),
            ],
        ),
        migrations.AlterField(
            model_name='guests',
            name='image_sample_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guests_img1', to='guests.Image'),
        ),
        migrations.AlterField(
            model_name='guests',
            name='image_sample_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guests_img2', to='guests.Image'),
        ),
        migrations.AlterField(
            model_name='guests',
            name='image_sample_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guests_img3', to='guests.Image'),
        ),
    ]
