# Generated by Django 3.0.8 on 2020-07-29 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0008_guests_rooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='guests',
            name='person_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
