# Generated by Django 3.0.8 on 2020-07-28 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty_program', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loyalty_program',
            options={'verbose_name': 'Loyalty Program', 'verbose_name_plural': 'Loyalty Program'},
        ),
    ]
