# Generated by Django 3.0.8 on 2020-07-28 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations_rooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservations_rooms',
            options={'verbose_name': 'Reservations Rooms', 'verbose_name_plural': 'Reservations Rooms'},
        ),
    ]
