# Generated by Django 3.0.8 on 2020-07-28 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations_rooms', '0002_auto_20200728_1450'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservations_rooms',
            name='checkin_date',
        ),
        migrations.RemoveField(
            model_name='reservations_rooms',
            name='num_of_days',
        ),
        migrations.RemoveField(
            model_name='reservations_rooms',
            name='num_of_guests',
        ),
        migrations.RemoveField(
            model_name='reservations_rooms',
            name='status',
        ),
    ]
