# Generated by Django 3.0.8 on 2020-07-28 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rooms',
            options={'verbose_name': 'Room', 'verbose_name_plural': 'Rooms'},
        ),
    ]
