# Generated by Django 2.1.15 on 2020-07-29 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_auto_20200728_1641'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rooms',
            name='amenities',
        ),
        migrations.AlterField(
            model_name='rooms',
            name='type',
            field=models.CharField(choices=[('SINGLE', 'SINGLE'), ('DOUBLE', 'DOUBLE'), ('DELUX', 'DELUX'), ('PRESIDENTIAL', 'PRESIDENTIAL')], max_length=128),
        ),
    ]
